baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Portfolio Nggaaa'
theme="nggaaa"
summarylength=20
[social]
    Github = 'nggaaa'
    Instagram = 'ng.gaaa'
    Youtube = 'channel/UCjzrGjLb5npoHj7owJFVDFg'
[params]
    Description="Portfolio"


[markup]
    [markup.highlight]
        anchorLineNos=false
        codeFences=true
        guessSyntax=false
        hl_Lines=''
        lineAnchors=''
        lineNoStart=1
        lineNos=true
        lineNumbersInTable=true
        noClasses=true
        noHl=false
        style="dracula"
        tabWidth=2